
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async greet(name: string) : Promise<string> {
    return await TAURI_INVOKE("greet", { name });
},
async ping() : Promise<string> {
    return await TAURI_INVOKE("ping");
},
async checkOllama() : Promise<Result<VersionResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_ollama") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listModels() : Promise<Result<TagsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkModelInstalled(model: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_model_installed", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pullModel(model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pull_model", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runAction(action: string, text: string, model: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_action", { action, text, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedText() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_text") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async replaceText(text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("replace_text", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async captureAndRun(action: string, model: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("capture_and_run", { action, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isAccessibilityTrusted() : Promise<boolean> {
    return await TAURI_INVOKE("is_accessibility_trusted");
},
async requestAccessibilityPermission() : Promise<boolean> {
    return await TAURI_INVOKE("request_accessibility_permission");
},
async openAccessibilitySettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_accessibility_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Diagnostic snapshot: TCC flag, functional-probe result, and the exact
 * executable that needs the grant. The frontend shows this when the
 * permission looks stuck (stale-entry scenario).
 */
async getAccessibilityStatus() : Promise<Result<AccessibilityStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_accessibility_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validateHotkey(hotkey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_hotkey", { hotkey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Accept from the popup: hide → restore source-app focus → paste → save to
 * history. Order matters — the popup holds keyboard focus, so it must be
 * hidden and the source app re-activated BEFORE the synthetic Cmd/Ctrl+V,
 * otherwise the paste lands in Quill.
 */
async acceptResult(text: string, original: string, action: string, model: string, refinements: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("accept_result", { text, original, action, model, refinements }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Popup refine chat: apply one instruction to the current version.
 * Stateless single round-trip (original + current + instruction).
 */
async refineResult(original: string, current: string, instruction: string, model: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refine_result", { original, current, instruction, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closePopup() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_popup") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPopupText() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_popup_text") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openUrl(url: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_url", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAutostart(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_autostart", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Settings> {
    return await TAURI_INVOKE("get_settings");
},
async saveSettings(settings: Settings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRecommendedModel() : Promise<string> {
    return await TAURI_INVOKE("get_recommended_model");
},
async getSystemRamGb() : Promise<number> {
    return await TAURI_INVOKE("get_system_ram_gb");
},
async showPopupCommand() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_popup_command") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hidePopupCommand() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_popup_command") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closePopupCommand() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_popup_command") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async registerHotkeyCommand(hotkey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register_hotkey_command", { hotkey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHotkey() : Promise<string> {
    return await TAURI_INVOKE("get_hotkey");
},
async isHotkeyRegistered(hotkey: string) : Promise<boolean> {
    return await TAURI_INVOKE("is_hotkey_registered", { hotkey });
},
async getHistoryEntries(cursor: number | null, limit: number | null) : Promise<Result<PaginatedHistory, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history_entries", { cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteHistoryEntry(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_history_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearHistory() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Diagnostic snapshot for the frontend, shown when the permission looks stuck
 * (almost always a stale TCC entry from an identity change).
 */
export type AccessibilityStatus = { 
/**
 * `AXIsProcessTrusted()`.
 */
trusted: boolean; 
/**
 * The exact executable that needs the grant — TCC keys on this identity.
 */
executablePath: string; 
/**
 * `false` when running the bare dev binary rather than `Quill.app`. The
 * two are distinct TCC entries; granting one does not grant the other.
 */
bundled: boolean; 
/**
 * For the `tccutil reset Accessibility <id>` hint.
 */
bundleIdentifier: string }
export type HistoryEntry = { id: number; 
/**
 * Unix seconds (UTC).
 */
timestamp: number; action: string; model: string; original_text: string; result_text: string; 
/**
 * Chat instructions applied during refinement, in order.
 */
refinements: string[] }
export type ModelInfo = { name: string; size: number | null; modified_at: string | null }
export type PaginatedHistory = { entries: HistoryEntry[]; has_more: boolean }
export type Settings = { model: string; hotkey: string; launchAtLogin: boolean; theme: Theme; onboardingComplete?: boolean }
export type TagsResponse = { models: ModelInfo[] }
export type Theme = "system" | "light" | "dark"
export type VersionResponse = { version: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
